using System;

class FirstClass
{
    public delegate void Event(string name);
    public event Event MyEvent;
    public string name;
    public FirstClass(string name)
    {
        this.name = name;
    }
    public void GenerateEvent()
    {
        if (MyEvent != null)
        {
            MyEvent.Invoke(name);
        }
    }
}

class SecondClass
{
    public void HandleEvent(string eventName)
    {
        Console.WriteLine("Event was generated by object: " + eventName);
    }
}

class Program
{
    static void Main(string[] args)
    {
        FirstClass firstObject1 = new FirstClass("First object 1");
        FirstClass firstObject2 = new FirstClass("First object 2");
        SecondClass secondObject = new SecondClass();

      
        firstObject1.MyEvent += secondObject.HandleEvent;
        firstObject2.MyEvent += secondObject.HandleEvent;

        firstObject1.GenerateEvent();
        firstObject2.GenerateEvent();
    }
}